# Generated by Django 3.0.2 on 2020-01-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbx',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
