# Generated by Django 3.0.2 on 2020-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbx', '0002_fbx_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbx',
            name='bump',
            field=models.FileField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fbx',
            name='fbx',
            field=models.FileField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fbx',
            name='normals',
            field=models.FileField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fbx',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fbx',
            name='texture',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
