# Generated by Django 3.0.2 on 2020-01-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbx', '0004_auto_20200112_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbx',
            name='bump',
            field=models.FileField(blank=True, max_length=200, upload_to='images/designs'),
        ),
        migrations.AlterField(
            model_name='fbx',
            name='normals',
            field=models.FileField(blank=True, max_length=200, upload_to='images/designs'),
        ),
        migrations.AlterField(
            model_name='fbx',
            name='texture',
            field=models.FileField(blank=True, max_length=200, upload_to='images/designs'),
        ),
    ]
