# Generated by Django 3.0.2 on 2020-01-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbx', '0005_auto_20200112_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbx',
            name='bump',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fbx',
            name='fbx',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fbx',
            name='normals',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fbx',
            name='texture',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
    ]
